from survey import AnonymousSurvey
mine=AnonymousSurvey('who you like to meet')
mine.show_question()
mine.store_response('2')
mine.store_response('2')
mine.store_response('qi')
mine.store_response('qi')
mine.store_response('qi')
mine.store_response('qi')
mine.store_response('qi')
mine.store_response('qi')
mine.store_response('qi')
mine.show_results()
